---
title: "Class 07"
author: "Varsha Rajesh"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Functions and CRAN

Write a function, called both_na(), that counts how many positions in two input vectors (x and y) BOTH have a missing value
```{r}
x <- c(1, 2, NA, 3, NA)  #First define two vectors x and y
y <- c(NA, 3, NA, 3, 4)
is.na(x)   #is.na function will tell you which elements in each vector are NA
is.na(y)
sum(is.na(x))   #sum all the times that element is NA
sum(is.na(x) & is.na(y))  #sum all the times BOTH elements are NA at the same time
#Our final function:
both_na <- function(x, y) {
  if (length(x) != length(y)) {
    stop("Input x and y should be the same length")
  }
  sum(is.na(x) & is.na(y))
}
```

Test function:
```{r}
both_na(x,y)
```

```{r}
rescale <- function(x, na.rm=TRUE, plot=FALSE, ...) {
 rng <-range(x, na.rm=na.rm)

 answer <- (x - rng[1]) / (rng[2] - rng[1])
 if(plot) {
 plot(answer, ...)
 }
 print("ABC")
 return(answer)
}
```

Gene Intersection:

```{r}
df1 <- data.frame(IDs=c("gene1", "gene2", "gene3"),exp=c(2,1,1), 
                  stringsAsFactors=FALSE)
df2 <- data.frame(IDs=c("gene2", "gene4", "gene3", "gene5"),exp=c(-2, NA, 1, 2),
                  stringsAsFactors=FALSE)
#Simplify further to single vectors
x <- df1$IDs
y <- df2$IDs

intersect(x,y)
#Which elements of x exist in y?
x %in% y 
#which elements of x fulfill the condition of being true?
x[x %in% y]

y[y %in% x]

cbind(x[x %in% y], y[y %in% x])
```

```{r}
gene_intersect <- function(x, y) {
  cbind(x[x%in%y], y[y%in%x])
}
gene_intersect(x,y)
#Write function that can extract info from the data frame itself without us having to define x and y

```

```{r}
gene_intersect2 <- function(a, b) {
  cbind(a[a$IDs%in%b$IDs, ], 
        b[b$IDs%in%a$IDs, ])
}
gene_intersect2(df1, df2)
```

```{r}
gene_intersect3 <- function(a, b) {
  cbind(a[a$IDs%in%b$IDs, ], 
        b[b$IDs%in%a$IDs, ])
}
df1 <- data.frame(IDs=c("gene1", "gene2", "gene3"),exp=c(2,1,1), 
                  stringsAsFactors=FALSE)
gene.colname = "IDs"
df1[,gene.colname]

```

```{r}
# student 1
student1 <- c(100, 100, 100, 100, 100, 100, 100, 90)
# student 2
student2 <- c(100, NA, 90, 90, 90, 90, 97, 80)

grade <- function(x) {
  count <- 0
  for(score in x) {
    if(score != min(x)) {
      count <- score + count
    }
  }
  print(count/(length(x)-1))
}
grade(student1)


```
```{r}
#ScatterplotPlot of sepal length vs sepal width for different iris species
ggplot(data = iris, aes(x=Sepal.Length, y=Sepal.Width, color = Species)) + geom_point(aes(shape = Species)) + geom_smooth(method = "lm")

#Bar plot 
ggplot(iris, aes(Sepal.Length, fill=Species))+geom_bar(stat = "count")
```




